### PR TITLE
1251070 - broken link fixed

### PR DESCRIPTION
**Pull request by v-hearya**

### CODE REVIEW

**Comment by jmazzotta** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/v-hearya/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ja-jp/blob/master/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md) | :warning:Warning | | [Details](#user-content-Web-Apps-Server-loc%2Fconfigure-office-web-apps-for-sharepoint-2013.md)

<a name="Web-Apps-Server-loc%2Fconfigure-office-web-apps-for-sharepoint-2013.md"></a>
### [Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/v-hearya/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ja-jp/blob/master/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md)
 - **Line 136**: **[Warning]** Invalid file link:(~/deploy-office-web-apps-server#office-web-apps-%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC-%E3%82%92%E5%AE%9F%E8%A1%8C%E3%81%99%E3%82%8B%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC%E3%81%AE%E6%BA%96%E5%82%99).
 - **Line 136**: **[Warning]** Invalid file link:(~/deploy-office-web-apps-server#http-%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%99%E3%82%8B-office-web-%E3%82%A2%E3%83%97%E3%83%AA%E3%82%B1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3-%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC-%E3%83%95%E3%82%A1%E3%83%BC%E3%83%A0%E3%81%AE-1-%E5%8F%B0%E3%81%AE%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC%E3%82%92%E5%B1%95%E9%96%8B%E3%81%97%E3%81%BE%E3%81%99).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C27%5C256b3780-f050-5510-de48-090f762cfd39%5CPullRequest%5C201806272220116219-6%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=OMQAhDwM%2FwX0k0CzC5B%2BTJkA268W%2FsB%2FmMAgYT9tGKo%3D&st=2018-06-27T22%3A16%3A18Z&se=2018-07-28T22%3A21%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jmazzotta** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/v-hearya/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ja-jp/blob/master/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md) | :warning:Warning | | [Details](#user-content-Web-Apps-Server-loc%2Fconfigure-office-web-apps-for-sharepoint-2013.md)

<a name="Web-Apps-Server-loc%2Fconfigure-office-web-apps-for-sharepoint-2013.md"></a>
### [Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/v-hearya/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ja-jp/blob/master/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md)
 - **Line 136**: **[Warning]** Invalid file link:(~/deploy-office-web-apps-server#https-%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%99%E3%82%8B%E5%8D%98%E4%B8%80%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC-office-web-apps-%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC-%E3%83%95%E3%82%A1%E3%83%BC%E3%83%A0%E3%81%AE%E5%B1%95%E9%96%8B).
 - **Line 136**: **[Warning]** Invalid file link:(~/deploy-office-web-apps-server#https-%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%99%E3%82%8B%E8%B2%A0%E8%8D%B7%E5%88%86%E6%95%A3%E3%81%95%E3%82%8C%E3%81%9F%E8%A4%87%E6%95%B0%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC-office-web-apps-%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC-%E3%83%95%E3%82%A1%E3%83%BC%E3%83%A0%E3%81%AE%E5%B1%95%E9%96%8B).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C27%5C256b3780-f050-5510-de48-090f762cfd39%5CPullRequest%5C201806272301266745-6%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=B78ON4fb3fhCYs4X6rlawXRe%2Bj9ipsZgYU2K0bZvH0I%3D&st=2018-06-27T22%3A57%3A36Z&se=2018-07-28T23%3A02%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jmazzotta** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/v-hearya/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ja-jp/blob/master/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md) | :warning:Warning | | [Details](#user-content-Web-Apps-Server-loc%2Fconfigure-office-web-apps-for-sharepoint-2013.md)

<a name="Web-Apps-Server-loc%2Fconfigure-office-web-apps-for-sharepoint-2013.md"></a>
### [Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/v-hearya/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ja-jp/blob/master/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md)
 - **Line 136**: **[Warning]** Invalid file link:(~/deploy-office-web-apps-server#https-%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%99%E3%82%8B%E5%8D%98%E4%B8%80%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC-office-web-apps-%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC-%E3%83%95%E3%82%A1%E3%83%BC%E3%83%A0%E3%81%AE%E5%B1%95%E9%96%8B).
 - **Line 136**: **[Warning]** Invalid file link:(~/deploy-office-web-apps-server#https-%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%99%E3%82%8B%E8%B2%A0%E8%8D%B7%E5%88%86%E6%95%A3%E3%81%95%E3%82%8C%E3%81%9F%E8%A4%87%E6%95%B0%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC-office-web-apps-%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC-%E3%83%95%E3%82%A1%E3%83%BC%E3%83%A0%E3%81%AE%E5%B1%95%E9%96%8B).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C29%5C256b3780-f050-5510-de48-090f762cfd39%5CPullRequest%5C201806292013233728-6%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=H2IIHhNJjkgOsVSrUqvOuer2FS%2FNvAZI0CwO6GR44Bc%3D&st=2018-06-29T20%3A09%3A31Z&se=2018-07-30T20%3A14%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jmazzotta** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/v-hearya/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ja-jp/blob/master/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md) | :warning:Warning | | [Details](#user-content-Web-Apps-Server-loc%2Fconfigure-office-web-apps-for-sharepoint-2013.md)
[.openpublishing.publish.config.json](https://github.com/v-hearya/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ja-jp/blob/master/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

<a name="Web-Apps-Server-loc%2Fconfigure-office-web-apps-for-sharepoint-2013.md"></a>
### [Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/v-hearya/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ja-jp/blob/master/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md)
 - **Line 136**: **[Warning]** Invalid file link:(~/deploy-office-web-apps-server#https-%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%99%E3%82%8B%E5%8D%98%E4%B8%80%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC-office-web-apps-%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC-%E3%83%95%E3%82%A1%E3%83%BC%E3%83%A0%E3%81%AE%E5%B1%95%E9%96%8B).
 - **Line 136**: **[Warning]** Invalid file link:(~/deploy-office-web-apps-server#https-%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%99%E3%82%8B%E8%B2%A0%E8%8D%B7%E5%88%86%E6%95%A3%E3%81%95%E3%82%8C%E3%81%9F%E8%A4%87%E6%95%B0%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC-office-web-apps-%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC-%E3%83%95%E3%82%A1%E3%83%BC%E3%83%A0%E3%81%AE%E5%B1%95%E9%96%8B).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C29%5C256b3780-f050-5510-de48-090f762cfd39%5CPullRequest%5C201806292021324470-6%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2ByQhuEzm%2BK4NcyYPTs5AiNh93L71%2Fn221Lb2tClhyqM%3D&st=2018-06-29T20%3A17%3A45Z&se=2018-07-30T20%3A22%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jmazzotta** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/v-hearya/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ja-jp/blob/master/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ja-jp/office/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013?branch=pr-ja-jp-6) | [Details](#user-content-Web-Apps-Server-loc%2Fconfigure-office-web-apps-for-sharepoint-2013.md)

<a name="Web-Apps-Server-loc%2Fconfigure-office-web-apps-for-sharepoint-2013.md"></a>
### [Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/v-hearya/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ja-jp/blob/master/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md)
 - **Line 136**: **[Warning]** Invalid file link:(~/deploy-office-web-apps-server#https-%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%99%E3%82%8B%E5%8D%98%E4%B8%80%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC-office-web-apps-%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC-%E3%83%95%E3%82%A1%E3%83%BC%E3%83%A0%E3%81%AE%E5%B1%95%E9%96%8B).
 - **Line 136**: **[Warning]** Invalid file link:(~/deploy-office-web-apps-server#https-%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%99%E3%82%8B%E8%B2%A0%E8%8D%B7%E5%88%86%E6%95%A3%E3%81%95%E3%82%8C%E3%81%9F%E8%A4%87%E6%95%B0%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC-office-web-apps-%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC-%E3%83%95%E3%82%A1%E3%83%BC%E3%83%A0%E3%81%AE%E5%B1%95%E9%96%8B).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C29%5C256b3780-f050-5510-de48-090f762cfd39%5CPullRequest%5C201806292213361182-6%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=slOXmq0%2BWPN3a4UvHviUj2ZbvCB%2FTXVRzyDqSU%2B6eWI%3D&st=2018-06-29T22%3A09%3A42Z&se=2018-07-30T22%3A14%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
Closing PR without merging as issue has been fixed

**Pull request closed without merging**
